#!/usr/bin/env python3
"""
summarize.py — Extract a context summary from a Claude Code JSONL transcript.

Usage:
    python3 summarize.py /path/to/transcript.jsonl          # Fast extraction
    python3 summarize.py --llm /path/to/transcript.jsonl    # LLM-powered (Haiku)
    tail -200 transcript.jsonl | python3 summarize.py

Output format:
    Working on: <goal> | Next: <step> | Files: <files>

Pattern reused from ~/.config/dotfiles/claude/code/hooks/pre-compact.py
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


def read_jsonl(source) -> list[dict]:
    messages = []
    for line in source:
        line = line.strip()
        if line:
            try:
                messages.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return messages


_BOILERPLATE_PATTERNS = [
    re.compile(
        r"Caveat: The messages below were generated by the user while running local commands\..*",
        re.DOTALL,
    ),
    re.compile(r"DO NOT respond to these messages.*", re.DOTALL),
]

# Messages to skip when looking for the "goal"
_SKIP_PATTERNS = [
    re.compile(r"^/\w"),  # slash commands: /exit, /model, /checkpoint, etc.
    re.compile(r"^(ok|yes|no|bye|sure|thanks|y|n|go|try it|do it|lgtm|done)\.?$", re.I),
    re.compile(r"^!"),  # shell commands
]

# Patterns that indicate an actionable next step in assistant messages
# All require word boundary \b to avoid mid-word matches
_NEXT_STEP_PATTERNS = [
    re.compile(r"\b(?:run|execute|try)\s*[:.]?\s*`(.+?)`", re.I),
    re.compile(r"^(?:next step|next)\s*[:.]?\s*(.+?)$", re.I | re.M),
    re.compile(r"\byou (?:should|need to|can now|could)\s+(.+?)[.]?$", re.I | re.M),
    re.compile(r"\b(?:shall I|should I|want me to)\s+(.+?)\??$", re.I | re.M),
]


def strip_xml_tags(text: str) -> str:
    """Remove XML-style tags, ANSI codes, and boilerplate injected by Claude Code."""
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\x1b\[[0-9;]*m", "", text)  # ANSI escape codes
    text = re.sub(r"\s{2,}", " ", text)
    text = text.strip()
    for pat in _BOILERPLATE_PATTERNS:
        text = pat.sub("", text).strip()
    return text


def extract_text(content) -> str:
    if isinstance(content, str):
        return strip_xml_tags(content.strip())
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                parts.append(strip_xml_tags(block["text"].strip()))
        return " ".join(parts)
    return ""


def extract_files_modified(messages: list[dict]) -> list[str]:
    files: set[str] = set()
    for msg in messages:
        role, content = unwrap_message(msg)
        if role != "assistant":
            continue
        if not isinstance(content, list):
            continue
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "tool_use":
                continue
            if block.get("name") in ("Edit", "Write"):
                fp = block.get("input", {}).get("file_path", "")
                if fp:
                    files.add(fp)
    return sorted(files)


def unwrap_message(msg: dict) -> tuple[str, any]:
    """Extract role and content from a JSONL entry."""
    inner = msg.get("message", msg)
    role = inner.get("role", "")
    content = inner.get("content", "")
    return role, content


def is_substantive(text: str) -> bool:
    """Check if a message is substantive (not a slash command, ack, or terminal output)."""
    if len(text) < 15:
        return False
    for pat in _SKIP_PATTERNS:
        if pat.match(text):
            return False
    # Skip terminal/build output (lots of special chars, ▸, [+], etc.)
    special_ratio = sum(1 for c in text[:200] if c in "▸[]+✔─│├└►→●") / min(len(text), 200)
    if special_ratio > 0.02:
        return False
    return True


def find_goal_message(user_messages: list[str]) -> str:
    """Find the first substantive user message as the session goal."""
    for msg in user_messages:
        if is_substantive(msg):
            # Take first sentence or first line, whichever is shorter
            first_line = msg.split("\n")[0].strip()
            sentences = re.split(r"(?<=[.!?])\s", first_line)
            goal = sentences[0] if sentences else first_line
            goal = goal[:200].strip()
            if len(goal) < 10 and len(first_line) > 10:
                goal = first_line[:200]
            return goal
    # Fallback: first sentence of first message
    if user_messages:
        first_line = user_messages[0].split("\n")[0].strip()
        return first_line[:200]
    return ""


def extract_next_step(assistant_messages: list[str]) -> str:
    """Extract the most actionable next step from recent assistant messages."""
    # Check last 3 assistant messages, newest first
    for msg in reversed(assistant_messages[-3:]):
        # Only match patterns at the start of a sentence (after period/newline or at start)
        for pat in _NEXT_STEP_PATTERNS:
            match = pat.search(msg)
            if match:
                step = match.group(1).strip()
                # Sanity check: step should be a coherent phrase, not a fragment
                if len(step) < 10 or len(step) > 300:
                    continue
                step = step[:200].replace("\n", " ")
                return step

    # Fallback: last sentence of last assistant message (if short enough to be actionable)
    if assistant_messages:
        last = assistant_messages[-1]
        # Split on sentence boundaries
        sentences = re.split(r"(?<=[.!?])\s+", last)
        sentences = [
            s.strip() for s in sentences
            if 15 < len(s.strip()) < 200
            and not s.strip().startswith("Estimated tokens")
            and not s.strip().startswith("Cost:")
        ]
        if sentences:
            return sentences[-1][:200].replace("\n", " ")
    return ""


def summarize(messages: list[dict], all_messages: Optional[list[dict]] = None) -> str:
    """Fast extraction-based summary.

    Args:
        messages: Recent messages (last 200) for next-step and file extraction.
        all_messages: Full transcript (if available) for goal extraction.
    """
    # Use full transcript for goal if available, otherwise recent messages
    goal_source = all_messages if all_messages else messages

    user_messages: list[str] = []
    assistant_messages: list[str] = []

    # Extract user messages from full transcript for goal
    for msg in goal_source:
        role, content = unwrap_message(msg)
        text = extract_text(content)
        if text and role == "user":
            user_messages.append(text)

    # Extract assistant messages from recent messages for next step
    for msg in messages:
        role, content = unwrap_message(msg)
        text = extract_text(content)
        if text and role == "assistant":
            assistant_messages.append(text)

    if not user_messages and not assistant_messages:
        return "No conversation content found."

    parts: list[str] = []

    # Working on: first substantive user message
    goal = find_goal_message(user_messages)
    if goal:
        parts.append(f"Working on: {goal}")

    # Next step from assistant
    next_step = extract_next_step(assistant_messages)
    if next_step:
        parts.append(f"Next: {next_step}")

    # Files modified
    files = extract_files_modified(messages)
    if files:
        if len(files) <= 4:
            parts.append(f"Files: {', '.join(Path(f).name for f in files)}")
        else:
            shown = ", ".join(Path(f).name for f in files[:4])
            parts.append(f"Files: {shown} and {len(files) - 4} more")

    return " | ".join(parts)


def summarize_llm(messages: list[dict]) -> Optional[str]:
    """LLM-powered summary using claude CLI (Haiku for speed + cost)."""
    # Build a condensed transcript from last 50 messages
    conversation: list[str] = []
    for msg in messages[-50:]:
        role, content = unwrap_message(msg)
        text = extract_text(content)
        if not text:
            continue
        # Truncate individual messages to keep prompt small
        text = text[:500]
        if role == "user":
            conversation.append(f"User: {text}")
        elif role == "assistant":
            conversation.append(f"Assistant: {text}")

    if not conversation:
        return None

    transcript = "\n".join(conversation[-30:])  # Last 30 exchanges max

    prompt = f"""Summarize this Claude Code session in exactly 2 sentences. No preamble.
Sentence 1: What was being worked on (the actual goal, not meta-commands like /exit or /model).
Sentence 2: What's the immediate next step or what's blocking progress.

Transcript:
{transcript}"""

    try:
        result = subprocess.run(
            [
                "claude",
                "-p", prompt,
                "--model", "haiku",
                "--bare",
                "--no-session-persistence",
            ],
            capture_output=True,
            text=True,
            timeout=15,
            env={**os.environ, "CLAUDE_CODE_SIMPLE": "1"},
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()[:500]
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass

    return None


def main():
    use_llm = "--llm" in sys.argv
    args = [a for a in sys.argv[1:] if a != "--llm"]

    all_messages = None
    if args:
        fpath = Path(args[0])
        if not fpath.exists():
            print(f"File not found: {fpath}", file=sys.stderr)
            sys.exit(1)
        with open(fpath) as f:
            lines = f.readlines()
        # Parse full transcript for goal, recent for next-step
        all_messages = read_jsonl(lines)
        messages = read_jsonl(lines[-200:])
    else:
        messages = read_jsonl(sys.stdin)

    if use_llm:
        llm_result = summarize_llm(all_messages or messages)
        if llm_result:
            print(llm_result)
            return

    # Fast extraction fallback
    print(summarize(messages, all_messages))


if __name__ == "__main__":
    main()
